
project_id = "feamvyruipxtafzhptkh"

[functions.zarinpal-contract]
verify_jwt = false

[functions.zarinpal-verify]
verify_jwt = false

[functions.zarinpal-checkout]
verify_jwt = false

[functions.marzneshin-update-user]
verify_jwt = false

[functions.marzneshin-search-user]
verify_jwt = false

[functions.refresh-panel-config]
verify_jwt = false

[functions.marzban-create-user]
verify_jwt = false
